### ISSUE TITLE
"sandbox run" gives error in centos as 'bash: sandbox: command not found'

### ISSUE THREAD

**Issue by pethirajan-apptium** [getsandbox/sandbox#22]
Hello,

I am very new to Sandbox and I am trying to setup Sandbox in my local, There are no step by step guide to follow.

All I tried to do is downloaded the Sandbox binary version, extracted the tar to a location '\home\app' and when I ran the 'sandbox run' command I am getting the error as 'bash: sandbox: command not found'

But I am able to use 'java -jar sandbox --port=8080 run'
and the result is 
Sandbox ready (build: v? runtime: VERSION_2) --  Running on port: 8080 with path: '/home/app'

my centos Linux IP is 192.168.56.100
But when i hit the URL  http://192.168.56.100:8080 I do not see service being up

**Comment by virgil-av** [comment]
Did you manage to make this work, I am more curios about sandbox as a new developer, I tried installing it on ubuntu 16 I  first installed the java requirement I extract the archive but I cannot run any commands sandbox run gives me a bash error and the other command gives me Unable to access jarfile sandbox

**Comment by nhoughto** [comment]
Sorry i've been away and missed this issue, long time open. OP looks like you are running fine, by default the server should be listening on 0.0.0.0, so across all interfaces on port 8080. Strange that you are not seeing it, are you making the request from the same machine? Could it be a firewall issue?

Yep doco on the runtime is light on, thanks for the feedback and improvements.

As the sandbox binary is just another binary, and isn't installed anyway per se, it should be run as per a normal binary, so './' is required if running from the current directory, otherwise /home/user/sandbox would work for a full path.
