### ISSUE TITLE
Sandbox binary within spring-boot application (Sandbox as a applications runtime)

### ISSUE THREAD

**Issue by pethirajan-apptium** [getsandbox/sandbox#25]
I tried to place the Sandbox jar in the classpath within the Java/Maven/spring-boot application and control the runtime. But I couldn't do this.. 
are there any better approach to achieve this other than placing the sandbox in the file system?

**Comment by nhoughto** [comment]
I've used this approach before to start sandbox and stop sandbox before/after spring-boot application under test with gradle:

https://gist.github.com/nhoughto/bf5c69fd0428847b2800d2bba42d0a83

Otherwise CLIBootstrap could be extended to expose a stop() method to allow control of the runtime from within the same JVM, PRs welcome.

**Comment by pethirajan-apptium** [comment]
currently I am killing the process tree (not a good approach).
But it sounds like exposing the stop() in CLIBootstrap is the better approach for me than the first one because I am are using maven.
I played around to just make use of the JavaBootstrap by including sandbox to classpath, but because of both spring/boot and sandbox uses different spring frameworks there is a problem while I am trying to start the spring/boot application.

**Comment by nhoughto** [comment]
Actually CLIBootstrap was the wrong class, you want JavaBootstrap

https://github.com/getsandbox/sandbox/blob/master/src/main/java/com/sandbox/runtime/config/JavaBootstrap.java
