### ISSUE TITLE
res.get() returns string "undefined" instead of undefined type

### ISSUE THREAD

**Issue by 2upmedia** [getsandbox/sandbox#6]
res.get() returns a string of "undefined" for a falsy value instead of an actual falsy value like `undefined`. This has consequences when you're trying to use the return value in conditional statements.

```javascript
var contentRange = res.get('Content-Range');
    
if (contentRange) { // "undefined"
    // unexpectedly enters
}
```

The current workaround is to specify the string of "undefined" in the conditional.

```javascript
if (contentRange !== "undefined") {
```

**Comment by nhoughto** [comment]
Hey

Will look into it, thanks for the feedback.

**Comment by 2upmedia** [comment]
I looked more into it and seems like it's a limitation of Nashorn. If Nashorn allows returning a javascript null, returning a `null` or the value in a string would be acceptable IMO.

**Comment by nhoughto** [comment]
Pretty sure this is why you're getting a String:

https://github.com/getsandbox/sandbox/blob/f543b499d770fdf48c463a4866cf3dd72ef1de6d/src/main/java/com/sandbox/runtime/models/HTTPRequest.java#L98

But you might be right, ill keep digging. If i tweak the method to return Object instead of String, it should return the internal Undefined obj that Nashorn will interpret as JS undefined. Have to look into other impacts as it might break compatibility for some people.

**Comment by nhoughto** [comment]
I think your example is wrong though, i can only replicate your behaviour with a req.get() not a res.get(). res.get() gives correct behaviour.

**Comment by 2upmedia** [comment]
Sorry about that, that was a typo. If the behavior correct that means getsandbox.com is running an older version.

**Comment by nhoughto** [comment]
Been fixed for a while.
