### ISSUE TITLE
[JS] faker.random.number() returns wrong numbers

### ISSUE THREAD

**Issue by harnash** [getsandbox/sandbox#7]
Hi.
I've noticed that when using `faker.random.number()` seems to return 0.0 or 1.0 which is not what I was expecting :-)

**Comment by nhoughto** [comment]
Yeah, while random that is definitely not as per expectations, random.uuid() doesn't work either. We will have a look. Thanks for the feedback.

**Comment by nhoughto** [comment]
Seems like faker ships their libraries with the max for number() set to 1 and precision set to 1,  so you will only ever get 0.0 or 1.0, but their examples on their website has the max set to 99999 giving the impression it is wrong.

You can set another max value by passing an option to number({max:99999}) for example, more options on the faker.js website.

uuid() wasn't in the version of faker we are using, upgrading to 2.1.5 which has it.

**Comment by harnash** [comment]
@nhoughto Thanks for reply. `max` option kinda works but I've notice two more inconsistencies:
1. It returns float instead of integer (which can be easily fixed though)
2. It always return the same number for each call (seems like seed is not being properly set) so I get the same sequence of random numbers between calls.

**Comment by nhoughto** [comment]
Hmm will investigate but I think this is faker expected behaviour,
1. precision is set at 1, but the number() function can return a number with decimal points, and JS doesn't really have 'integers' and 'floats' it really just has numbers, so kinda the same? Other than if you are rendering it to a string I suppose.
2. I feel like this is faker behaviour, internally faker uses its own PRNG, appears to set the seed using current timestamp when initialised.

**Comment by harnash** [comment]
Yeah. I did some testing and it seems this is probably some representation problem or it is platform specific. It seems that in Chrome `math.floor(1.2)` will print out `1` but in nashorn it will print `1.0`. My JavaScript skill are to low to draw any conclusions from that.
